appname: gopush
port: 8081
addr: 127.0.0.1
postgresql:
    dbType:       postgresql
    dbName:       chatdb
    dbUserName:   dbuser
    dbPassword:   dbuser123
    port:         5432
jwt:
    key:  token-key-123
json:
    pretty:   true
