appname: gopush
port: 8081
addr: 127.0.0.1
postgresql:
    dbType:       "postgres"
    dbName:       "chatdb"
    dbUserName:   "dbuser"
    dbPassword:   "dbuser123"
    dbPort:         5432
    dbHost:         "127.0.0.1"
    dbDebug:        true
jwt:
    key:  "token-key-123"
json:
    pretty:   true
tcp:
    address:        "127.0.0.1"
    maxConnCount:   10
    acceptCount:    10
redis:
    host:   "127.0.0.1"
    port:   6379
    password:     ""
    maxIdle:    10
    maxActive:  10000
    wait:   true
    dbNum: 0